@base=http://localhost:3000/api

# @name login
POST {{base}}/user/login
Content-Type: application/json

{
    "password": "123456",
    "username": "test1"
}
### 保存登录接口拿到的token
@token={{login.response.body.$.data.token}}

### 查询销售订单列表
GET {{base}}/saleOrder
Authorization: Bearer {{token}}

### 生成出货单
POST {{base}}/saleOrder
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "platformId": 2,
    "platformOrderNo": "pdd001",
    "remark": "",
    "expressId": 1,
    "expressNo": "yd001",
    "expressFee": 10,
    "saleTrolleyId": 1,
    "products": [
        {
            "vendorId": 2,
            "price": 1,
            "count": 1,
            "productId": 3
        },
        {
            "vendorId": 3,
            "price": 8,
            "count": 1,
            "productId": 4
        }
    ]
}

### 出货列表详情
GET {{base}}/saleOrder/1
Authorization: Bearer {{token}}

### 修改出货单商品数量
PUT {{base}}/saleOrder/1
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "productId": 4
}

### 补充出货单的辅助信息
PATCH {{base}}/saleOrder/updateAuxiliaryInfo/4
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "expressFee": 10,
    "expressId": 1,
    "expressNo": "yd001",
    "platformId": 2,
    "platformOrderNo": "pdd001"
}