@base=http://localhost:3000/api

# @name login
POST {{base}}/user/login
Content-Type: application/json

{
    "username": "test1",
    "password": "123456"
}
### 保存登录接口拿到的token
@token={{login.response.body.$.data.token}}

### product list
# &minCost=90&maxCost=210
GET {{base}}/product?limit=10&page=1
Authorization: Bearer {{token}}


### 商品详情
GET {{base}}/product/getProductById/1
Authorization: Bearer {{token}}

### create product
POST {{base}}/product
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "手机贴膜",
    "vendorId": 2
}
### 前十库存商品
GET {{base}}/product/productTopCount
Authorization: Bearer {{token}}

### 前十库存商品
GET {{base}}/product/topValueProduct
Authorization: Bearer {{token}}

### 更新商品
PUT {{base}}/product/updateProductById/1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "手机贴膜"
}

### 删除商品
PATCH {{base}}/product/toggleAvailable/1
Authorization: Bearer {{token}}