@base=http://localhost:3000/api
@token2 =eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOm51bGwsInVzZXJuYW1lIjoiZmVybmFuZG8iLCJjcmVhdGVBdCI6IjIwMjUtMDMtMDJUMDg6Mjc6NDkuNjI3WiIsInVwZGF0ZUF0IjoiMjAyNS0wMy0wMlQwODoyNzo0OS42MjdaIiwiYXZhdGFyIjpudWxsLCJyb2xlIjoic3RhZmYiLCJpc0RlbCI6ZmFsc2UsImlhdCI6MTc0MDk4OTA0NywiZXhwIjoxNzQxMDc1NDQ3fQ.aQIv5brAWrQ7lshQ37Q5MVPU40-5UlrpivgiehxaUCk

# @name login
POST {{base}}/user/login
Content-Type: application/json

{
    "username": "test4",
    "password": "123456"
}
### 保存登录接口拿到的token
@token={{login.response.body.$.data.token}}

### user list
GET {{base}}/trolley?limit=10&page=1&name=beer
Authorization: Bearer {{token}}

### create trolley
POST {{base}}/trolley
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "price": 2, 
    "count": 3, 
    "productId": 3
}

### update trolley 添加新的商品
PUT {{base}}/trolley/8
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "price": 2, 
    "count": 3, 
    "productId": 3,
    "operation": "create"
}


### update trolley 修改已有商品的数量
PUT {{base}}/trolley/8
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "price": 20, 
    "count": 1, 
    "productId": 3,
    "operation": "update"
}

### update trolley 删除已存在的商品
PUT {{base}}/trolley/8
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "productId": 3,
    "price": 20, 
    "count": 1, 
    "operation": "delete"
}

### get trolleyDetail
GET {{base}}/trolley
Authorization: Bearer {{token}}


### delete trolleyDetail
DELETE {{base}}/trolley/6?productId=1
Authorization: Bearer {{token}}

